In [43]:
import numpy as np

pref = np.array([[21, 32, 49, 34],
              [10, 38, 50, 13],
              [22, 13, 28, 23]])

print(pref)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]


In [44]:
total_participants = np.sum(pref)
print(f"a total of {total_participants} participated in the study")
#print(total_participants.shape)

a total of 333 participated in the study


In [45]:
totals_by_column = np.sum(pref,axis=0)
print(totals_by_column)
#print(totals_by_column.shape)

[ 53  83 127  70]


In [46]:
participants_per_study = np.sum(pref,axis=1)
print(participants_per_study)
#print(participants_per_study.shape)

[136 111  86]


In [47]:
percent_by_row = pref / participants_per_study
print(percent_by_row)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [48]:
# perhaps try making it 2D?
participants_per_study_2d = np.array([participants_per_study])
print(participants_per_study_2d)
#print(participants_per_study_2d.shape)

[[136 111  86]]


In [49]:
percent_by_row = pref / participants_per_study_2d
print(percent_by_row)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [50]:
# double check
print(pref.shape)
print(participants_per_study.shape)
print(participants_per_study_2d.shape)

(3, 4)
(3,)
(1, 3)


In [59]:
# SO, RESHAPE participants_per_study to the shape we need
participants_per_study = participants_per_study.reshape(x,x)
percent_by_row = pref / participants_per_study
print(percent_by_row)

NameError: name 'x' is not defined

In [52]:
# the 2D array reshaped is also good
participants_per_study_2d = participants_per_study_2d.reshape(3,1)
percent_by_row = pref / participants_per_study_2d
print(percent_by_row)

[[0.15441176 0.23529412 0.36029412 0.25      ]
 [0.09009009 0.34234234 0.45045045 0.11711712]
 [0.25581395 0.15116279 0.3255814  0.26744186]]


In [60]:
# instead of hardcoding in the 3, have NumPy figure out what number we need
participants_per_study = np.sum(pref,axis=1).reshape(-1,1)
percent_by_row = pref / participants_per_study
print(percent_by_row)

[[0.15441176 0.23529412 0.36029412 0.25      ]
 [0.09009009 0.34234234 0.45045045 0.11711712]
 [0.25581395 0.15116279 0.3255814  0.26744186]]


In [54]:
# OR JUST CREATE THE SHAPE AS WE NEED IT
participants_per_study = np.sum(pref,axis=1,keepdims=True)
percent_by_row = pref / participants_per_study
print(percent_by_row)

[[0.15441176 0.23529412 0.36029412 0.25      ]
 [0.09009009 0.34234234 0.45045045 0.11711712]
 [0.25581395 0.15116279 0.3255814  0.26744186]]


In [55]:
print(np.sum(percent_by_row,axis=1))

[1. 1. 1.]


In [56]:
# Let's turn them into nice percentages
percent_by_row *= 100
print(percent_by_row)

[[15.44117647 23.52941176 36.02941176 25.        ]
 [ 9.00900901 34.23423423 45.04504505 11.71171171]
 [25.58139535 15.11627907 32.55813953 26.74418605]]


In [58]:
print(np.sum(percent_by_row,axis=1))

[100. 100. 100.]
