In [2]:
import numpy as np
a1 = np.empty((2,3))
a1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
a2 = np.ones((2,3)).astype(np.int64)
a2

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a3 = np.array([4,0.3,9])    # UPCAST
a3

array([4. , 0.3, 9. ])

In [15]:
a4 = np.arange(2,10,3)
a4

array([2, 5, 8])

In [5]:
a5 = np.arange(10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a5[6] = 23
a5

array([ 0,  1,  2,  3,  4,  5, 23,  7,  8,  9])

In [7]:
a5[2:8]

array([ 2,  3,  4,  5, 23,  7])

In [9]:
a5[3:5] = 16
a5

array([ 0,  1,  2, 16, 16,  5, 23,  7,  8,  9])

In [10]:
a6 = a5[2:8]
a6

array([ 2, 16, 16,  5, 23,  7])

In [13]:
a6[0] = 0
print(a6)
print(a5)

[ 0 16 16  5 23  7]
[ 0  1  0 16 16  5 23  7  8  9]


In [17]:
a4[:] = 6
a4

array([6, 6, 6])

In [18]:
a7 = np.arange(20).reshape(4,5)
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
a7[1]

array([5, 6, 7, 8, 9])

In [20]:
a7[0,0]

np.int64(0)

In [21]:
a7[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
a7[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a7[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a7[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [25]:
a7[:,:1]

array([[ 0],
       [ 5],
       [10],
       [15]])

In [26]:
a7[:,-2:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])