In [ ]:
import numpy as np

rng = np.random.default_rng()
grades = rng.normal(85,7,23).astype(np.int64)
print(grades)

In [ ]:
grades[0] += 10
print(grades)

grades[0] -= 10 # reset zeroth student
print(grades)


In [ ]:
# how to add 10 to all students' grades?

grades +=10
print(grades)

In [ ]:
grades[[0,9,12]] += 10
print(grades)

In [ ]:
grades[[3,19]] += 5
print(grades)

In [ ]:
grades2d = rng.normal(85,7,(10,4)).astype(np.int64)
print(grades2d)

[[ 70  91  84  86]
 [ 81  81  88  77]
 [ 79 103  84  81]
 [ 78  87  86  89]
 [ 89  83  92  82]
 [ 87  83  67  83]
 [ 90  82  79  89]
 [ 87 100  97  79]
 [ 85  91  75  79]
 [ 85  86  84  86]]


In [ ]:
grades2d[[0,2]]

In [ ]:
grades2d[[0,2],[1,3]]

In [ ]:
grades2d[:,[1,3]]

In [ ]:
# compare this with next. view or copy?
slice_view = grades2d[:3, :2]
print(slice_view)
slice_view[0,0] = 999
print(slice_view)
print(grades2d)



In [ ]:
# compare this one with the previous. view or copy?
grades1and3 = grades2d[:,[1,3]]
print(grades1and3)
grades1and3[0,0] = 999
print(grades1and3)
print(grades2d)

In [ ]:
# rewrite previous as view
# grades1and3 = grades2d[:,[1,3]]

#print(grades1and3)






view_or_copy = grades2d[:,1:4:2]
print(view_or_copy)
view_or_copy[0,0]=999
print(view_or_copy)
print(grades2d)

In [ ]:
print(grades2d[3,1])
print(grades2d[[3,1]])

In [26]:

print(grades2d)
now_its_a_copy = grades2d[::2, :2].copy()       # view
print(now_its_a_copy)



[[ 70  91  84  86]
 [ 81  81  88  77]
 [ 79 103  84  81]
 [ 78  87  86  89]
 [ 89  83  92  82]
 [ 87  83  67  83]
 [ 90  82  79  89]
 [ 87 100  97  79]
 [ 85  91  75  79]
 [ 85  86  84  86]]
[[ 70  91]
 [ 79 103]
 [ 89  83]
 [ 90  82]
 [ 85  91]]


In [27]:
now_its_a_copy[1,1] = 888
print(now_its_a_copy)
print(grades2d)

[[ 70  91]
 [ 79 888]
 [ 89  83]
 [ 90  82]
 [ 85  91]]
[[ 70  91  84  86]
 [ 81  81  88  77]
 [ 79 103  84  81]
 [ 78  87  86  89]
 [ 89  83  92  82]
 [ 87  83  67  83]
 [ 90  82  79  89]
 [ 87 100  97  79]
 [ 85  91  75  79]
 [ 85  86  84  86]]


In [28]:
final_exam = grades2d[:, 2]  # third column (exam 3)
final_exam

array([84, 88, 84, 86, 92, 67, 79, 97, 75, 84])

In [31]:
final_exam >= 80
print(final_exam.shape)

(10,)


In [32]:
pass_mask = final_exam >= 80
print(final_exam.shape)
print("pass_mask:", pass_mask)


(10,)
pass_mask: [ True  True  True  True  True False False  True False  True]


In [33]:
print(f"length of final_exam array: {final_exam.size}")
print(f"length of pass_mask array: {pass_mask.size}")


length of final_exam array: 10
length of pass_mask array: 10


In [40]:
final_exam[final_exam >= 80]

array([84, 88, 84, 86, 92, 97, 84])

In [ ]:
print("passing scores:", final_exam[pass_mask])


print("count passing:", final_exam[pass_mask].size)

passing scores: [84 88 84 86 92 97 84]
count passing: 7


In [ ]:
grades2d & 32

In [ ]:
grades2d | 16

In [36]:
# Scores in a "B range": 80–89 inclusive (1D example)
mask_B = (final_exam >= 80) & (final_exam <= 89)
print("B-range scores:", final_exam[mask_B])

B-range scores: [84 88 84 86 84]


In [37]:
# Low OR High (1D example)
mask_low_or_high = (final_exam < 70) | (final_exam >= 90)
print("low OR high:", final_exam[mask_low_or_high])

low OR high: [92 67 97]


In [ ]:
print("final_exam min:", final_exam.min())
print("final_exam max:", final_exam.max())
print("final_exam mean:", final_exam.mean())
print("final_exam sum:", final_exam.sum())

final_exam min: 67
final_exam max: 97
final_exam mean: 83.6
final_exam sum: 836


In [39]:
print("grades2d min:", grades2d.min())
print("grades2d max:", grades2d.max())
print("grades2d mean:", grades2d.mean())
print("grades2d sum:", grades2d.sum())

grades2d min: 67
grades2d max: 103
grades2d mean: 84.625
grades2d sum: 3385


In [ ]:
import numpy as np
arr = np.array([12,23,34])
print(arr)
print(arr.dtype)
arr[1] = 3.14   # DOWNCAST
print(arr)

arr = np.array([12,23.4,34])    #UPCAST
print(arr)
print(arr.dtype)


[12 23 34]
int64
[12  3 34]
[12.  23.4 34. ]
float64


In [ ]:
# NO WE DID NOT COVER THE REST OF THE NOTEBOOK
sorted_final = np.sort(final_exam)  # returns sorted copy
print("sorted final:", sorted_final)
print(f"highest 3: {sorted_final[]}")

In [ ]:
# print lowest 3 finals

print(f"lowest 3 grades on final: {sorted_final[:3]}")

In [ ]:
# print highest 3 final grades
# 1. lowest to highest





print(f"highest final grades, lowest to highest {sorted_final[-3:]}")





In [ ]:
# 2. highest to lowest





print(f"highest grades, highest to lowest {sorted_final[-1:-4:-1]}")

#or 
sorted_final[-3:][::-1]






[12 23 34]
int64
[12  3 34]
[12.  23.4 34. ]
float64
