In [198]:
import numpy as np

rng = np.random.default_rng()
grades = rng.normal(85,7,23).astype(np.int64)
print(grades)

[ 78  91  73  83  80  82  78  78  93  75  81  87  79  69  87  74 100  80
  87  92  75  86  86]


In [199]:
grades[0] += 10
print(grades)

grades[0] -= 10 # reset zeroth student
print(grades)


[ 88  91  73  83  80  82  78  78  93  75  81  87  79  69  87  74 100  80
  87  92  75  86  86]
[ 78  91  73  83  80  82  78  78  93  75  81  87  79  69  87  74 100  80
  87  92  75  86  86]


In [200]:
# how to add 10 to all students' grades?

In [201]:
grades[[0,9,12]] += 10
print(grades)

[ 88  91  73  83  80  82  78  78  93  85  81  87  89  69  87  74 100  80
  87  92  75  86  86]


In [202]:
grades[[3,19]] += 5
print(grades)

[ 88  91  73  88  80  82  78  78  93  85  81  87  89  69  87  74 100  80
  87  97  75  86  86]


In [203]:
grades2d = rng.normal(85,7,(10,4)).astype(np.int64)
print(grades2d)

[[ 64  80  89  72]
 [ 85  80  80 101]
 [ 88  90  97  90]
 [ 90  73  92  85]
 [ 88  88  84  89]
 [ 86  82  72  77]
 [ 81  83  82  80]
 [ 86  83  81  89]
 [ 91  84  71  81]
 [ 82  87  84  77]]


In [204]:
grades2d[[0,2]]

array([[64, 80, 89, 72],
       [88, 90, 97, 90]])

In [205]:
grades2d[[0,2],[1,3]]

array([80, 90])

In [206]:
grades2d[:,[1,3]]

array([[ 80,  72],
       [ 80, 101],
       [ 90,  90],
       [ 73,  85],
       [ 88,  89],
       [ 82,  77],
       [ 83,  80],
       [ 83,  89],
       [ 84,  81],
       [ 87,  77]])

In [207]:
# compare this with next. view or copy?
slice_view = grades2d[:3, :2]
print(slice_view)
slice_view[0,0] = 999
print(slice_view)
print(grades2d)



[[64 80]
 [85 80]
 [88 90]]
[[999  80]
 [ 85  80]
 [ 88  90]]
[[999  80  89  72]
 [ 85  80  80 101]
 [ 88  90  97  90]
 [ 90  73  92  85]
 [ 88  88  84  89]
 [ 86  82  72  77]
 [ 81  83  82  80]
 [ 86  83  81  89]
 [ 91  84  71  81]
 [ 82  87  84  77]]


In [208]:
# compare this one with the previous. view or copy?
grades1and3 = grades2d[:,[1,3]]
print(grades1and3)
grades1and3[0,0] = 999
print(grades1and3)
print(grades2d)

[[ 80  72]
 [ 80 101]
 [ 90  90]
 [ 73  85]
 [ 88  89]
 [ 82  77]
 [ 83  80]
 [ 83  89]
 [ 84  81]
 [ 87  77]]
[[999  72]
 [ 80 101]
 [ 90  90]
 [ 73  85]
 [ 88  89]
 [ 82  77]
 [ 83  80]
 [ 83  89]
 [ 84  81]
 [ 87  77]]
[[999  80  89  72]
 [ 85  80  80 101]
 [ 88  90  97  90]
 [ 90  73  92  85]
 [ 88  88  84  89]
 [ 86  82  72  77]
 [ 81  83  82  80]
 [ 86  83  81  89]
 [ 91  84  71  81]
 [ 82  87  84  77]]


In [209]:
# rewrite previous as view
# grades1and3 = grades2d[:,[1,3]]

print(grades1and3)



view_or_copy = grades2d[:,1:4:2]
print(view_or_copy)

[[999  72]
 [ 80 101]
 [ 90  90]
 [ 73  85]
 [ 88  89]
 [ 82  77]
 [ 83  80]
 [ 83  89]
 [ 84  81]
 [ 87  77]]
[[ 80  72]
 [ 80 101]
 [ 90  90]
 [ 73  85]
 [ 88  89]
 [ 82  77]
 [ 83  80]
 [ 83  89]
 [ 84  81]
 [ 87  77]]


In [210]:
print(grades2d[3,1])
print(grades2d[[3,1]])

73
[[ 90  73  92  85]
 [ 85  80  80 101]]


In [211]:

print(grades2d)
now_its_a_copy = grades2d[::2, :2].copy()       # view
print(now_its_a_copy)



[[999  80  89  72]
 [ 85  80  80 101]
 [ 88  90  97  90]
 [ 90  73  92  85]
 [ 88  88  84  89]
 [ 86  82  72  77]
 [ 81  83  82  80]
 [ 86  83  81  89]
 [ 91  84  71  81]
 [ 82  87  84  77]]
[[999  80]
 [ 88  90]
 [ 88  88]
 [ 81  83]
 [ 91  84]]


In [212]:
now_its_a_copy[1,1] = 888
print(now_its_a_copy)
print(grades2d)

[[999  80]
 [ 88 888]
 [ 88  88]
 [ 81  83]
 [ 91  84]]
[[999  80  89  72]
 [ 85  80  80 101]
 [ 88  90  97  90]
 [ 90  73  92  85]
 [ 88  88  84  89]
 [ 86  82  72  77]
 [ 81  83  82  80]
 [ 86  83  81  89]
 [ 91  84  71  81]
 [ 82  87  84  77]]


In [213]:
final_exam = grades2d[:, 2]  # third column (exam 3)
final_exam

array([89, 80, 97, 92, 84, 72, 82, 81, 71, 84])

In [214]:
pass_mask = final_exam >= 80
print("pass_mask:", pass_mask)


pass_mask: [ True  True  True  True  True False  True  True False  True]


In [215]:
print(f"length of final_exam array: {final_exam.size}")
print(f"length of pass_mask array: {pass_mask.size}")


length of final_exam array: 10
length of pass_mask array: 10


In [216]:
print("passing scores:", final_exam[pass_mask])
print("count passing:", final_exam[pass_mask].size)

passing scores: [89 80 97 92 84 82 81 84]
count passing: 8


In [221]:
grades2d & 32

array([[32,  0,  0,  0],
       [ 0,  0,  0, 32],
       [ 0,  0, 32,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [222]:
grades2d | 16

array([[1015,   80,   89,   88],
       [  85,   80,   80,  117],
       [  88,   90,  113,   90],
       [  90,   89,   92,   85],
       [  88,   88,   84,   89],
       [  86,   82,   88,   93],
       [  81,   83,   82,   80],
       [  86,   83,   81,   89],
       [  91,   84,   87,   81],
       [  82,   87,   84,   93]])

In [218]:
# Scores in a "B range": 80–89 inclusive (1D example)
mask_B = (final_exam >= 80) & (final_exam <= 89)
print("B-range scores:", final_exam[mask_B])

B-range scores: [89 80 84 82 81 84]


In [219]:
# Low OR High (1D example)
mask_low_or_high = (final_exam < 70) | (final_exam >= 90)
print("low OR high:", final_exam[mask_low_or_high])

low OR high: [97 92]


In [ ]:
print("final_exam min:", final_exam.min())
print("final_exam max:", final_exam.max())
print("final_exam mean:", final_exam.mean())
print("final_exam sum:", final_exam.sum())

final_exam min: 71
final_exam max: 97
final_exam mean: 83.2
final_exam sum: 832


In [224]:
print("grades2d min:", grades2d.min())
print("grades2d max:", grades2d.max())
print("grades2d mean:", grades2d.mean())
print("grades2d sum:", grades2d.sum())

grades2d min: 71
grades2d max: 999
grades2d mean: 106.975
grades2d sum: 4279


In [ ]:
# IF TIME
sorted_final = np.sort(final_exam)  # returns sorted copy
print("sorted final:", sorted_final)
print(f"highest 3: {sorted_final[]}")

sorted final: [71 72 80 81 82 84 84 89 92 97]


In [227]:
# print lowest 3 finals

print(f"lowest 3 grades on final: {sorted_final[:3]}")

lowest 3 grades on final: [71 72 80]


In [ ]:
# print highest 3 final grades
# 1. lowest to highest





print(f"highest final grades, lowest to highest {sorted_final[-3:]}")





highest grades, highest to lowest [97 92 89]


array([97, 92, 89])

In [ ]:
# 2. highest to lowest





print(f"highest grades, highest to lowest {sorted_final[-1:-4:-1]}")

#or 
sorted_final[-3:][::-1]






highest final grades, lowest to highest [89 92 97]
