In [2]:
import numpy as np

In [22]:
a = np.array([1,2,3])

print(a.shape)
print(a.ndim)

(3,)
1


In [23]:
b = np.array([[1,2,3]])

print(b.shape)
print(b.ndim)

(1, 3)
2


In [ ]:
c = np.array([1],[2],[3])   # i have a mistake here. what is it?

print(c.shape)
print(c.ndim)

In [21]:
d = np.array(1)
print(d.shape)
print(d.ndim)

()
0


In [7]:
arr1 = np.arange(12)
print(f"ndim: {arr1.ndim}, shape: {arr1.shape}")

arr2 = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print(f"ndim: {arr2.ndim}, shape: {arr2.shape}")

print(np.array_equal(arr1,arr2))    # value and shape check

# access element
arr1[1] = 100
print(arr1)

ndim: 1, shape: (12,)
ndim: 1, shape: (12,)
True
[  0 100   2   3   4   5   6   7   8   9  10  11]


In [ ]:
arr1 = np.arange(12).reshape(1,12)
print(f"ndim: {arr1.ndim}, shape: {arr1.shape}")

arr2 = np.array([[0,1,2,3,4,5,6,7,8,9,10,11]])
print(f"ndim: {arr2.ndim}, shape: {arr2.shape}")

print(np.array_equal(arr1,arr2))    # value and shape check

# access element
arr1[0][1] = 100
arr1[0,2] = 200
print(arr1)

ndim: 2, shape: (1, 12)
ndim: 2, shape: (1, 12)
True
[[  0 100 200   3   4   5   6   7   8   9  10  11]]


In [15]:
arr1 = np.arange(12).reshape(12,1)
print(f"ndim: {arr1.ndim}, shape: {arr1.shape}")

arr2 = np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11]])
print(f"ndim: {arr2.ndim}, shape: {arr2.shape}")

print(np.array_equal(arr1,arr2))    # value and shape check

# access element
arr1[1][0] = 100
print(arr1)

ndim: 2, shape: (12, 1)
ndim: 2, shape: (12, 1)
True
[[  0]
 [100]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]]


In [9]:
arr1 = np.arange(12).reshape(3,4)
print(f"ndim: {arr1.ndim}, shape: {arr1.shape}")

arr2 = np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])
print(f"ndim: {arr2.ndim}, shape: {arr2.shape}")

print(np.array_equal(arr1,arr2))    # value and shape check

# access element
arr1[0][1] = 100
print(arr1)

ndim: 2, shape: (3, 4)
ndim: 2, shape: (3, 4)
True
[[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [10]:
arr1 = np.arange(12).reshape(2,2,3)
print(f"ndim: {arr1.ndim}, shape: {arr1.shape}")

arr2 = np.array([[[0,1,2],
                  [3,4,5]],
                 [[6,7,8],
                  [9,10,11]]])
print(f"ndim: {arr2.ndim}, shape: {arr2.shape}")

print(np.array_equal(arr1,arr2))    # value and shape check

# access element
arr1[0][0][1] = 100
print(arr1)

ndim: 3, shape: (2, 2, 3)
ndim: 3, shape: (2, 2, 3)
True
[[[  0 100   2]
  [  3   4   5]]

 [[  6   7   8]
  [  9  10  11]]]


In [44]:
# BROADCASTING
# SHAPES ALIKE

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(f"arr1 shape: {arr1.shape}, arr2 shape: {arr2.shape}. Same? {arr1.shape==arr2.shape}")

print(arr1+arr2)

arr1 shape: (3,), arr2 shape: (3,). Same? True
[5 7 9]


In [45]:
# BROADCASTING.  IF SHAPES DON'T MATCH, NUMPY TRIES TO STRETCH
# NDIMs **DO** MATCH
arr1 = np.array([1,2,3])
arr2 = np.array([4])
print(f"shape, {arr1.shape} vs {arr2.shape} doesn't match, ndim, {arr1.ndim} vs {arr2.ndim} DOES match")

# IF ALL VALUES ARE EQUAL OR ONE, STRETCH
print(arr1+arr2)

shape, (3,) vs (1,) doesn't match, ndim, 1 vs 1 DOES match
[5 6 7]


In [ ]:
# BROADCASTING.  IF SHAPES DON'T MATCH, NUMPY TRIES TO STRETCH
# NDIMs **DO** MATCH
arr1 = np.array([1,2,3])
arr2 = np.array([4,5])
print(f"shape, {arr1.shape} vs {arr2.shape} doesn't match, ndim, {arr1.ndim} vs {arr2.ndim} DOES match")

# IF ALL VALUES ARE EQUAL OR ONE, STRETCH
print(arr1+arr2)

shape, (3,) vs (2,) doesn't match, ndim, 1 vs 1 DOES match
all values are NOT ALL EQUAL OR ONE


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [48]:
# BROADCASTING.  IF SHAPES DON'T MATCH, NUMPY TRIES TO STRETCH
# NDIMs **DON'T** MATCH
arr1 = np.array([1,2,3])
arr2 = np.array(4)
print(f"shape, {arr1.shape} vs {arr2.shape} doesn't match, ndim, {arr1.ndim} vs {arr2.ndim} don't match")

# PAD SHAPE ON LEFT UNTIL SAME NUMBER OF DIMENSIONS.
# IF ALL VALUES ARE EQUAL OR ONE, STRETCH
print(arr1+arr2)

shape, (3,) vs () doesn't match, ndim, 1 vs 0 don't match
[5 6 7]


In [51]:
# BROADCASTING.  IF SHAPES DON'T MATCH, NUMPY TRIES TO STRETCH
# NDIMs **DON'T** MATCH
# (SAME ARRAYS BUT EACH IS A DIMENSION HIGHER)
arr1 = np.array([[1,2,3]])
arr2 = np.array([4])
print(f"shape, {arr1.shape} vs {arr2.shape} doesn't match, ndim, {arr1.ndim} vs {arr2.ndim} don't match")

# PAD SHAPE ON LEFT UNTIL SAME NUMBER OF DIMENSIONS.
# IF ALL VALUES ARE EQUAL OR ONE, STRETCH
print(arr1+arr2)

shape, (1, 3) vs (1,) doesn't match, ndim, 2 vs 1 don't match
[[5 6 7]]


In [52]:
# BROADCASTING.  IF SHAPES DON'T MATCH, NUMPY TRIES TO STRETCH
# NDIMs **DON'T** MATCH
arr1 = np.array([[1,2,3]])
arr2 = np.array([4,5])
print(f"shape, {arr1.shape} vs {arr2.shape} doesn't match, ndim, {arr1.ndim} vs {arr2.ndim} don't match")

# PAD SHAPE ON LEFT UNTIL SAME NUMBER OF DIMENSIONS.
# IF ALL VALUES ARE EQUAL OR ONE, STRETCH
print(arr1+arr2)

shape, (1, 3) vs (2,) doesn't match, ndim, 2 vs 1 don't match


ValueError: operands could not be broadcast together with shapes (1,3) (2,) 

In [50]:
# print 12 x multiplication table
# ????????????
arr1 = np.arange(1,13)
arr2 = np.arange(1,13)
print(arr1*arr2)

[  1   4   9  16  25  36  49  64  81 100 121 144]


In [56]:
# SOME MORE EXAMPLES

M = np.ones((2,3))
a = np.arange(3)

print(M)
print(a)
print(f"M.ndim = {M.ndim}, M.shape = {M.shape}")
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}")

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
M.ndim = 2, M.shape = (2, 3)
a.ndim = 1, a.shape = (3,)


In [57]:
# NUMBER OF DIMENSIONS MISMATCH, PAD ON LEFT
# a.shape gets padded to (1,3)
# (2,3) vs
# (1,3)
# for each dimension, it is either the same value or a one in the position
# therefore, we can stretch a to (2,3) and do the addition:
print(M+a)

[[1. 2. 3.]
 [1. 2. 3.]]


In [65]:
a = np.arange(3).reshape(3,1)
b = np.arange(3)
print(a)
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}")
print(b)
print(f"b.ndim = {b.ndim}, b.shape = {b.shape}")

[[0]
 [1]
 [2]]
a.ndim = 2, a.shape = (3, 1)
[0 1 2]
b.ndim = 1, b.shape = (3,)


In [64]:
# NDIM **NOT** SAME, SO PAD SHAPE ON LEFT.  b's SHAPE becomes (1,3)
# (3,1) vs
# (1,3)
# ARE ALL EITHER THE SAME OR ONE?  YES.  STRETCH BOTH, THEY BOTH BECOME (3,3) and can add
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [66]:
M = np.ones((3,2))
a = np.arange(3)

print(M)
print(a)
print(f"M.ndim = {M.ndim}, M.shape = {M.shape}")
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}")

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]
M.ndim = 2, M.shape = (3, 2)
a.ndim = 1, a.shape = (3,)


In [ ]:
# NDIM **NOT** SAME, SO PAD SHAPE ON LEFT. shape of a becomes (1,3)
# (3,2) vs
# (1,3)
# 3 vs 1 OK.  2 vs 3, NOT OK
# NOT COMPATIBLE
print(M+a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 