In [143]:
import numpy as np

arr = np.array([40,10,30,20])
print(np.sort(arr))

[10 20 30 40]


In [144]:
print(arr)

[40 10 30 20]


In [145]:
arr.sort()

print(arr)

[10 20 30 40]


In [146]:
print(arr.sort())

None


In [147]:
rng = np.random.default_rng(seed=3225)
arr2 = rng.uniform(0,100,24).astype(np.int64)
print(arr2)

[90 95 40 82 86 92 18 75  9  7 92 61 48  2 70 81 72 81 34 85 69 21 44 51]


In [148]:
print(np.sort(arr2))
print(np.sort(arr2)[::-1])

[ 2  7  9 18 21 34 40 44 48 51 61 69 70 72 75 81 81 82 85 86 90 92 92 95]
[95 92 92 90 86 85 82 81 81 75 72 70 69 61 51 48 44 40 34 21 18  9  7  2]


In [149]:
#print(arr.sort()[::-1])    # DOES NOT WORK

In [150]:
#equivalent to previous
print(arr2)
print(np.flip(np.sort(arr2)))

[90 95 40 82 86 92 18 75  9  7 92 61 48  2 70 81 72 81 34 85 69 21 44 51]
[95 92 92 90 86 85 82 81 81 75 72 70 69 61 51 48 44 40 34 21 18  9  7  2]


In [151]:
#2D arrays
A = np.array([[3,1,2],[9,7,8]])

In [152]:
print(np.sort(A, axis=1))

[[1 2 3]
 [7 8 9]]


In [153]:
print(np.sort(A,axis=0))

[[3 1 2]
 [9 7 8]]


In [154]:
# very briefly
B = np.array([
    [[9,1],[4,2]],
    [[3,7],[8,6]]
])
print(B)
print(np.sort(B, axis= 2))

[[[9 1]
  [4 2]]

 [[3 7]
  [8 6]]]
[[[1 9]
  [2 4]]

 [[3 7]
  [6 8]]]


In [155]:
rng = np.random.default_rng(seed=3225)
arr3 = rng.uniform(0,100,(4,4)).astype(np.int64)
print(arr3)

[[90 95 40 82]
 [86 92 18 75]
 [ 9  7 92 61]
 [48  2 70 81]]


In [156]:
A = np.array([[3,1,2],[9,7,8]])

In [157]:
print(np.sort(arr3))
print(np.sort(arr3)[::-1])

[[40 82 90 95]
 [18 75 86 92]
 [ 7  9 61 92]
 [ 2 48 70 81]]
[[ 2 48 70 81]
 [ 7  9 61 92]
 [18 75 86 92]
 [40 82 90 95]]


In [158]:
# print each row in reverse

In [159]:
#np.flip(np.sort(arr3))

In [160]:
namesarr = np.array(["Amy","Bob","Cal","Dan","Eve"])
gradesarr = np.array([94,87,96,76,80])

for n, g in zip(namesarr,gradesarr):
    print(f"{n}: {g}")

Amy: 94
Bob: 87
Cal: 96
Dan: 76
Eve: 80


In [161]:
# how to print students in order of their grades??

print(np.sort(gradesarr))

[76 80 87 94 96]


In [162]:
print(np.sort(namesarr))

['Amy' 'Bob' 'Cal' 'Dan' 'Eve']


In [163]:
np.argsort(gradesarr)

array([3, 4, 1, 0, 2])

In [164]:
gradesarr[np.argsort(gradesarr)]

array([76, 80, 87, 94, 96])

In [165]:
namesarr[np.argsort(gradesarr)]

array(['Dan', 'Eve', 'Bob', 'Amy', 'Cal'], dtype='<U3')

In [166]:
namesarr[np.argsort(gradesarr)][::-1]

array(['Cal', 'Amy', 'Bob', 'Eve', 'Dan'], dtype='<U3')

In [167]:
namesarr[np.argsort(gradesarr)[::-1]]

array(['Cal', 'Amy', 'Bob', 'Eve', 'Dan'], dtype='<U3')